### ISSUE TITLE
Autocrafting causes NPE in Tinkers' Construct

### ISSUE THREAD

**Issue by iarspider** [Vswe/Production#28]
Steve's Workshop 0.5.1
Tinkers' Construct 1.8.5 
Iguana Tinkers Tweaks 2.1.5

```
[12:27:04] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$ItemCraftedEvent@1e52b72b:
java.lang.NullPointerException
        at tconstruct.tools.TinkerToolEvents.onCrafting(TinkerToolEvents.java:39) ~[TinkerToolEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_277_TinkerToolEvents_onCrafting_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570) [FMLCommonHandler.class:?]
        at vswe.production.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:109) [UnitCrafting.class:?]
        at vswe.production.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:92) [UnitCrafting.class:?]
        at vswe.production.page.unit.UnitCrafting.onProduction(UnitCrafting.java:529) [UnitCrafting.class:?]
        at vswe.production.page.unit.Unit.produce(Unit.java:156) [Unit.class:?]
        at vswe.production.page.unit.Unit.onUpdate(Unit.java:186) [Unit.class:?]
        at vswe.production.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:270) [UnitCrafting.class:?]
        at vswe.production.page.PageMain.onUpdate(PageMain.java:53) [PageMain.class:?]
        at vswe.production.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:323) [TileEntityTable.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[12:27:04] [Server thread/ERROR] [FML]: Index: 8 Listeners:
[12:27:04] [Server thread/ERROR] [FML]: 0: NORMAL
[12:27:04] [Server thread/ERROR] [FML]: 1: ASM: thaumcraft.common.lib.events.EventHandlerWorld@6e60d14 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 2: ASM: cofh.thermalexpansion.util.crafting.TECraftingHandler@6228392c handleOnItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 3: ASM: WayofTime.alchemicalWizardry.common.achievements.AchievementTrigger@dfd80a onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 4: ASM: vazkii.botania.common.item.ItemCraftingHalo@a3b444f onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 5: ASM: vazkii.botania.common.achievement.AchievementTriggerer@4ff1d2fc onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 6: ASM: mods.railcraft.common.util.crafting.CraftingHandler@7053cb7d onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 7: ASM: enchiridion.EventsHandler@6bf3572c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 8: ASM: tconstruct.tools.TinkerToolEvents@2b9b11ea onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 9: ASM: tconstruct.smeltery.TinkerSmelteryEvents@44eff54d onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 10: ASM: minetweaker.mc1710.FMLEventHandler@b522c9f onPlayerItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 11: ASM: mods.immibis.ccperiphs.ImmibisPeripherals$CraftingHandler@4e4be956 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 12: ASM: pneumaticCraft.common.recipes.CraftingHandler@6210812f onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 13: ASM: jotato.practicalities.EventHookContainer@19144310 onRadiantChargerCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 14: ASM: com.domochevsky.quiverbow.Listener@5a4bbcc7 ItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 15: ASM: tonius.simplyjetpacks.crafting.PlatingReturnHandler@7ded6e1a onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 16: ASM: appeng.core.stats.AchievementCraftingHandler@3d5c1394 onPlayerCraftingEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 17: ASM: buildcraft.core.utils.CraftingHandler@273d3727 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 18: ASM: tuhljin.automagy.lib.events.AutomagyEventHandler@2cfbae4c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 19: ASM: de.eydamos.backpack.handler.EventHandlerBackpack@52ab1b9f itemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 20: ASM: twilightforest.TFEventListener@30a8b372 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 21: ASM: li.cil.oc.common.EventHandler$@36844d8 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 22: ASM: mekanism.common.recipe.BinRecipe@262c2cbb onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 23: ASM: pl.asie.computronics.util.achievements.ComputronicsAchievements@1b810bda onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 24: ASM: thaumic.tinkerer.common.item.SpellClothCraftingHandler@5adb0dc3 ItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 25: ASM: fox.spiteful.forbidden.FMEventHandler@13336de6 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 26: ASM: com.jaquadro.minecraft.gardentrees.core.handlers.ForgeEventHandler@4f841a8e handleCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 27: ASM: xreliquary.event.CommonEventHandler@6c6c938b onCraftingPotion(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 28: ASM: xreliquary.event.CommonEventHandler@6c6c938b onCraftingAlkahest(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 29: ASM: mcjty.rftools.FMLEventHandlers@d86727e onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 30: ASM: stevesaddons.recipes.ClusterUncraftingRecipe@7f5d8acd onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 31: ASM: vswe.stevescarts.Helpers.CraftingHandler@669205d7 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 32: ASM: tconstruct.weaponry.WeaponryHandler@1509aa0e onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 33: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.LevelingEventHandler@169398b2 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 34: ASM: iguanaman.iguanatweakstconstruct.AntiChiselDupeHandler@65ea6b38 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[12:27:04] [Server thread/ERROR] [FML]: 35: LOWEST
[12:27:04] [Server thread/ERROR] [FML]: 36: ASM: org.blockartistry.mod.ThermalRecycling.AchievementManager@17f0f875 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
```

**Comment by ProsperCraft** [comment]
This is scrolling in the server console constantly - 
FTB Evolved 2.1.2

TConstruct-1.7.10-1.8.8.jar
StevesWorkshop-0.5.1.jar

http://pastebin.com/81fEp5GR

[10:23:39 ERROR]: Index: 9 Listeners:                                                                                                                                            │···········
[10:23:39 ERROR]: 0: NORMAL                                                                                                                                                      │···········
[10:23:39 ERROR]: 1: ASM: ic2.core.IC2Achievements@1a93e357 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                                            │···········
[10:23:39 ERROR]: 2: ASM: WayofTime.alchemicalWizardry.common.achievements.AchievementTrigger@9e6421 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V│···········
[10:23:39 ERROR]: 3: ASM: thaumcraft.common.lib.events.EventHandlerWorld@4270c74f onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                      │···········
[10:23:39 ERROR]: 4: ASM: vazkii.botania.common.item.ItemCraftingHalo@1c37f3ca onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                      │···········
[10:23:39 ERROR]: 5: ASM: vazkii.botania.common.achievement.AchievementTriggerer@76a41be onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V            │···········
[10:23:39 ERROR]: 6: ASM: cofh.thermalexpansion.util.crafting.TECraftingHandler@ecb31ae handleOnItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V       │···········
[10:23:39 ERROR]: 7: ASM: mods.railcraft.common.util.crafting.CraftingHandler@4f77355d onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                 │···········
[10:23:39 ERROR]: 8: ASM: com.brandon3055.draconicevolution.common.achievements.Achievements@27333f7c craftEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V  │···········
[10:23:39 ERROR]: 9: ASM: tconstruct.tools.TinkerToolEvents@6b6a5eca onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                                   │···········
[10:23:39 ERROR]: 10: ASM: tconstruct.smeltery.TinkerSmelteryEvents@78aa1d14 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                           │···········
[10:23:39 ERROR]: 11: ASM: minetweaker.mc1710.FMLEventHandler@61b0a29f onPlayerItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                        │···········
[10:23:39 ERROR]: 12: ASM: appeng.core.stats.AchievementCraftingHandler@a824d6f onPlayerCraftingEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V             │···········
[10:23:39 ERROR]: 13: ASM: buildcraft.core.AchievementManager@46ff2be2 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                                 │···········
[10:23:39 ERROR]: 14: ASM: twilightforest.TFEventListener@392d5617 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                                     │···········
[10:23:39 ERROR]: 15: ASM: blusunrize.immersiveengineering.common.EventHandler@6802216e onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V             │···········
[10:23:39 ERROR]: 16: ASM: thaumic.tinkerer.common.item.SpellClothCraftingHandler@edc70cf ItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V             │···········
[10:23:39 ERROR]: 17: ASM: fox.spiteful.forbidden.FMEventHandler@7aa2e853 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                              │···········
[10:23:39 ERROR]: 18: ASM: mcjty.rftools.FMLEventHandlers@4ac22a1d onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                             │···········
[10:23:39 ERROR]: 19: ASM: tonius.simplyjetpacks.crafting.PlatingReturnHandler@35c34e51 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V             │···········
[10:23:39 ERROR]: 20: ASM: stevesaddons.recipes.ClusterUncraftingRecipe@19f8202e onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                       │···········
[10:23:39 ERROR]: 21: ASM: vswe.stevescarts.Helpers.CraftingHandler@5b41d228 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                           │···········
[10:23:39 ERROR]: 22: ASM: tconstruct.weaponry.WeaponryHandler@7c8a8cb3 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V                                │···········
[10:23:39 WARN]: java.lang.NullPointerException                                                                                                                                  │···········
[10:23:39 WARN]:        at tconstruct.tools.TinkerToolEvents.onCrafting(TinkerToolEvents.java:39)                                                                                │···········
[10:23:39 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_319_TinkerToolEvents_onCrafting_ItemCraftedEvent.invoke(.dynamic)                                    │···········
[10:23:39 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)                                                                      │···········
[10:23:39 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)                                                                                     │···········
[10:23:39 WARN]:        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:591)                                                               │···········
[10:23:39 WARN]:        at vswe.production.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:109)                                                                               │···········
[10:23:39 WARN]:        at vswe.production.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:92)                                                                               │···········
[10:23:39 WARN]:        at vswe.production.page.unit.UnitCrafting.onProduction(UnitCrafting.java:529)                                                                            │···········
[10:23:39 WARN]:        at vswe.production.page.unit.Unit.produce(Unit.java:156)                                                                                                 │···········
[10:23:39 WARN]:        at vswe.production.page.unit.Unit.onUpdate(Unit.java:186)                                                                                                │···········
[10:23:39 WARN]:        at vswe.production.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:270)                                                                                │···········
[10:23:39 WARN]:        at vswe.production.page.PageMain.onUpdate(PageMain.java:53)                                                                                              │···········
[10:23:39 WARN]:        at vswe.production.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:323)                                                                    │···········
[10:23:39 WARN]:        at net.minecraft.world.World.func_72939_s(World.java:2513)                                                                                               │···········
[10:23:39 WARN]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)                                                                                    │···········
[10:23:39 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)                                                                           │···········
[10:23:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)                                                                 │···········
[10:23:39 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)                                                                           │···········
[10:23:39 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)                                                                                    │···········
[10:23:39 WARN]:        at java.lang.Thread.run(Thread.java:745)                                                                                                                 │···········
